services:
  nginx:
      container_name: nginx
      image: nginx:latest
      volumes:
        - ./config/nginx.conf:/etc/nginx/nginx.conf
        - ./config/server.conf:/etc/nginx/conf.d/default.conf
        - ./data/:/usr/share/nginx/html/data
        - ./config/.htpasswd:/etc/nginx/.htpasswd
      ports:
        - '80:80'
      restart: unless-stopped
